'''
Create a program that will play the “cows and bulls” game with the user. The
game works like this:
Randomly generate a 4-digit number. Ask the user to guess a 4-digit number.
For every digit that the user guessed correctly in the correct place, they have a
“cow”. For every digit the user guessed correctly in the wrong place is a “bull”.
Every time the user makes a guess, tell them how many “cows” and “bulls” they
have. Once the user guesses the correct number, the game is over. Keep track of
the number of guesses the user makes throughout the game and tell the user at
the end.
Say the number generated by the computer is 1038. An example interaction
could look like this:
BUCI033S7 Page 2 of 3 ©Birkbeck 2018
Welcome to the Cows and Bulls Game!
Enter a number:
 1234
2 cows, 0 bulls 1256
1 cow, 1 bull
...
Until the user guesses the number.


'''
import random


def check_guess(guess,random_number):
    '''
    Check that guess is not correct
    :param guess:
    :param random_number:
    :return:
    '''
    return guess == random_number
def convert_to_list(number):
    '''

    :param number:
    :return:
    '''
    storage_list = []
    for char in number:
        storage_list.append(char)
    return storage_list

def cows_bulls(guess,random_number):

    for index in range(0,len(guess)):
        if number in random_number:
            for correct_number in random_number:
                if number == correct_number





random_number = random.randint(0,9999)
# initial value
guess = -1

while not check_guess(guess,random_number):
    guess = str(input("Please enter your guess:"))
    cows_bulls_score = cows_bulls(guess,random_number)